docs: add pytorch training notebook
docarray/docarray pull request #1011
Opened 2023-01-11 16:42 UTC by samsja

# Context

add a example notebook to showcase DocArray with pytorch and fastapi

2023-01-12 14:02 UTC, JohannesMessner requested changes

2023-01-12 14:14 UTC, samsja commented on docs/tutorials/mutlimodal_training_and_serving.md
> +        return self.linear(x)
hmmm I think we want to avoid this inplace things. What about multi embedding etc ?

2023-01-16 11:11 UTC, JohannesMessner requested changes

2023-01-16 11:11 UTC, JohannesMessner commented on README.md
> +function
```suggestion
Looks much better, doesn't it?
You instantly win in code readability and maintainability. And for the same price you can turn your PyTorch model into a FastAPI app and reuse your Document
schema definition (see below). Everything handles in a pythonic manner by relying on type hints.
```

2023-01-16 11:13 UTC, samsja commented on README.md
> +    image_tensor: Optional[TorchTensor]
it fails otherwise because the image we load the line after does not have this shape

2023-01-16 11:14 UTC, samsja commented on README.md
> +<!-- #region -->
what is this region stuff ?

2023-01-16 11:19 UTC, JohannesMessner commented on README.md
> +    image_tensor: Optional[TorchTensor]
Can we use the correct shape then? I think this is a cool feature to showcase

2023-01-17 14:24 UTC, samsja commented on README.md
> +    image_tensor: Optional[TorchTensor]
done

2023-01-17 14:42 UTC, merged