fix: fix csv string parsing and memory leak in dataset
docarray/docarray pull request #1044
Opened 2023-01-23 13:31 UTC by Jackmin801

- line.split(",") does not take into account cases where there are commas in the caption
- the copy in getitem isnt deep, causing a memory leak

2023-01-23 15:02 UTC, samsja approved these changes

2023-01-23 15:02 UTC, samsja requested changes
can u add pip install pandas in the begining of the notebook ?

2023-01-23 15:05 UTC, Jackmin801 commented
Oh I think jupyter notebooks come with pandas tho

2023-01-23 16:57 UTC, samsja approved these changes

2023-01-24 08:38 UTC, JohannesMessner approved these changes

2023-01-24 09:05 UTC, merged