feat: init text directly
docarray/docarray pull request #1067
Opened 2023-01-31 16:33 UTC by JoanFM

Goals:
Solves #1056 

Allows to have a less-verbose `Text` initalization:

```python
from docarray.documents import Text
Text('hello world')
``` 
works

2023-01-31 17:06 UTC, samsja requested changes
can we add it to the docstring ?

2023-01-31 17:09 UTC, JoanFM commented
> can we add it to the docstring ?

Check now

2023-01-31 17:39 UTC, JoanFM commented
partially fix : https://github.com/docarray/docarray/issues/1056

2023-02-01 09:00 UTC, JohannesMessner approved these changes

2023-02-01 09:11 UTC, samsja approved these changes

2023-02-01 09:11 UTC, merged