Fix update tensor
docarray/docarray pull request #1148
Opened 2023-02-20 09:14 UTC by samsja

# Context

wip, fix : https://github.com/docarray/docarray/issues/1081 I will add more info once I am done with the implementation

2023-02-24 14:38 UTC, JohannesMessner commented
For archival purposes I'm adding the Discord discussion around this issue: https://discord.com/channels/1062677585999429653/1078671075761725560/1078685668617769060

2023-02-24 15:54 UTC, JoanFM requested changes
I would like to understand better how the view is implemented in Pytorch. Keeping a circular dependency does not seem to me as appropiate

2023-02-24 16:22 UTC, JoanFM commented
What happens if we put the Document into another `DocumentArrayStacked`? Then to whom does it belong?

2023-02-24 16:31 UTC, samsja commented
> I would like to understand better how the view is implemented in Pytorch. Keeping a circular dependency does not seem to me as appropiate

In Pytorch they have a circular dependency as well. The view and the original object share the same storage object.

Btw I wanted to use weakref originally to avoid memory problem. Turn out it messed up the multiprocessing part (not sure why). But I found out that python is able to deal with cyclic reference so it is not a problem

2023-02-24 16:33 UTC, samsja commented
> > I would like to understand better how the view is implemented in Pytorch. Keeping a circular dependency does not seem to me as appropiate
> 
> In Pytorch they have a circular dependency as well. The view and the original object share the same storage object.
> 
> Btw I wanted to use weakref originally to avoid memory problem. Turn out it messed up the multiprocessing part (not sure why). But I found out that python is able to deal with cyclic reference so it is not a problem

But maybe @JoanFM you are right I should be more careful. Should I add a test to see if the GC handles it properly?

2023-02-24 16:35 UTC, samsja commented
@JoanFM what would be an alternative according to you (I am open to any alternative tbh). The thing is that conceptually if a document update triggers a da update then they need to somehow be linked right ?

2023-02-24 16:36 UTC, samsja commented
> What happens if we put the Document into another `DocumentArrayStacked`? Then to whom does it belong?

This is not possible. The new DocumentArray will check that there are no `_da_ref` in the document before allowing him.

Basically, oncee a Document is appended to a DocumentArrayStack it is the da that has full ownership of the doc

2023-02-27 09:30 UTC, JohannesMessner requested changes
I have three questions:
1. when stacking a da, the small tensor that get stacked up get "destroyed", right?
2. for this PR, would it make sense to define a dedicated class for Documents that are in a stacked DA, something like `DocumentView`? I think it would make code separation a bit clearer, and also clarify some concepts.
3. If we do 2., then would it make sense to store all data on the array level, and nothing on the document level (for `DocumentArrayStacked` only)? Even if it isn't truly stacked, then it would be just a list. And accessing a Document in the stacked da returns a `DocumentView`, which is rally just a view into the array? I think it would complete our `view` narrative and make it as close to torch, np etc. as possible

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +                    f'{doc} already belong to {doc._da_ref} and cannot be stack again'
```suggestion
                    f'{doc} already belongs to {doc._da_ref} and cannot be stacked again'
```
Maybe I would say something like `doc is a view of [...] and cannot be stacked again`

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +    def stacked_field(self) -> Iterable[str]:
```suggestion
    def stacked_fields(self) -> Iterable[str]:
```

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +    def __update_columns__(self, field_name: str, da_index: int, value: Any) -> Any:
why is this a dunder method?

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +        """This function allow to update a column value in place
```suggestion
        """This function allows to update a column value in-place
```

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +        :return: return the updated view of the column with the value data
```suggestion
        :return: return the updated view of the column, at position `da_index`, with the `value` data
```

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +    def __update_columns__(self, field_name: str, da_index: int, value: Any) -> Any:
can value really be Any?

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +                    'DocumentArrayStack column level directly'
```suggestion
                    'Tensorflow tensors are immutable, therefore '
                    'you cannot change the tensor value of a stacked '
                    'DocumentArray with Tensorflow. You should either unstack your '
                    'DocumentArrayStacked or work at the '
                    'DocumentArrayStacked column level directly.'
```

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/array/stacked/array_stacked.py
> +                    'DocumentArrayStack column level directly'
not sure what this "work at column level directly" means

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/base_document/document.py
> +        return self._da_ref is not None
I would make this public and call it `is_view` or something like that

2023-02-27 09:30 UTC, JohannesMessner commented on docarray/base_document/document.py
> +    ref: 'DocumentArrayStacked'
I would call this `parent_da` or something like that instead of `ref`, which is very non-descript

2023-03-06 08:22 UTC, samsja commented
new PR : https://github.com/docarray/docarray/pull/1183

2023-03-06 08:22 UTC, closed without merging