feat: search_field  should be optional in hybrid text search
docarray/docarray pull request #1516
Opened 2023-05-09 08:11 UTC by AnneYang720

This PR is related to issue #1504

2023-05-09 13:05 UTC, hsm207 requested changes
Which PR has the update for the docs?

2023-05-10 00:54 UTC, AnneYang720 commented
> Which PR has the update for the docs?

I just updated the doc here.

2023-05-10 09:50 UTC, hsm207 approved these changes

2023-05-10 10:43 UTC, JoanFM requested changes

2023-05-10 10:43 UTC, JoanFM commented on docs/user_guide/storing/index_weaviate.md
> +    )  # No need to set search_field as it has no effect in hybird search
I think there is no need to add this annotation here. I as a user I would not see why you mention something that is not there

2023-05-10 11:46 UTC, JoanFM approved these changes

2023-05-10 11:46 UTC, merged