fix: detach the torch tensors
docarray/docarray pull request #1526
Opened 2023-05-10 12:19 UTC by makram93

Detach `TorchTensors` before converting to `numpy` for serialization. 

Change is only needed for PyTorch as Tensorflow operates differently afaik. I have tried different initialization for tensorflow and the below serializing script worked without any error.

```python

import time

from docarray import BaseDoc
from docarray.typing import TensorFlowTensor
import tensorflow as tf

class MyDoc(BaseDoc):
    x: TensorFlowTensor
    y: TensorFlowTensor

# 1. Eager execution with GradientTape
x = tf.Variable(3.0)  # trainable: Default: `True`, GradientTapes automatically watch uses of this variable.

with tf.GradientTape() as tape:
    y = x**2

doc = MyDoc(x=x, y=y)
doc.json()

# 2. GradientTape with tf.function
@tf.function
def square(a):
    return a**2

x = tf.Variable(tf.random.normal((3, 2)))

with tf.GradientTape() as tape:
    y = square(x)

doc = MyDoc(x=x, y=y)
doc.json()

# 3. TF constants
x = tf.Variable(tf.random.normal((3, 2)))
y = tf.constant(2.0)

doc = MyDoc(x=x, y=y)
doc.json()

# 4. Full example
w = tf.Variable(tf.random.normal((3, 2)), name="w")
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name="b")
x = [[1.0, 2.0, 3.0]]

with tf.GradientTape(persistent=True) as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y**2)

[dl_dw, dl_db] = tape.gradient(loss, [w, b])

doc = MyDoc(x=dl_dw, y=dl_db)
doc.json()

```

2023-05-10 13:27 UTC, JoanFM requested changes
can you please add a test for the case reported in the issue?

2023-05-10 14:01 UTC, JohannesMessner requested changes

2023-05-10 14:01 UTC, JohannesMessner commented on docarray/typing/tensor/torch_tensor.py
> +        return self.detach().numpy()  # might need to check device later
This only seems to tackle json serialization. Do al the other ones work? Protobuf, pickle, etc?

2023-05-10 14:02 UTC, JoanFM requested changes

2023-05-10 14:02 UTC, JoanFM commented on tests/units/typing/tensor/test_torch_tensor.py
> +    doc = MyDoc(tens=torch.rand(10, requires_grad=False))
can we please use `parametrization`? Like this, when a test fails is easier to identify which failed.

Also, can u do some sort of assertion on the output of this `json` method?

2023-05-11 07:09 UTC, JoanFM approved these changes

2023-05-11 07:10 UTC, merged