fix: add empty judgement to index search
docarray/docarray pull request #1533
Opened 2023-05-12 13:53 UTC by AnneYang720

This PR is related to issue #1530 .

2023-05-12 14:06 UTC, JoanFM requested changes
can we check what happens with other backends?

2023-05-15 07:15 UTC, JoanFM approved these changes

2023-05-15 08:38 UTC, JoanFM requested changes

2023-05-15 08:38 UTC, JoanFM commented on docarray/index/backends/hnswlib.py
> +        if not self.num_docs():
do == 0

2023-05-15 08:38 UTC, JoanFM commented on docarray/index/backends/in_memory.py
> +        if not self.num_docs():
can u do ==0?

2023-05-15 08:46 UTC, JoanFM approved these changes

2023-05-15 08:48 UTC, jupyterjazz commented
@JoanFM  only hnsw failed when the index was empty, others are doing well

2023-05-15 09:03 UTC, merged