fix: validate file formats in url
docarray/docarray pull request #1606
Opened 2023-05-31 16:46 UTC by makram93

Solves: #1555 

Solution:
- rely on `mimetypes` library to detect the mime type from the URL and raise error if it is not the expected type for that class
- make a URL request and read from the header, if the URL alone is insufficient.
- if auto-detection of mime-type fails then we check if the file ending is among the `allowed extensions`

2023-05-31 16:54 UTC, JoanFM commented
I think doing a request to the URL is an overkill and it will make it very slow

2023-05-31 16:54 UTC, JoanFM requested changes

2023-05-31 16:54 UTC, JoanFM commented on docarray/typing/url/any_url.py
> +            try:
avoid this step

2023-05-31 16:56 UTC, makram93 commented on docarray/typing/url/any_url.py
> +            try:
okay, will remove it!

2023-06-26 09:04 UTC, JoanFM approved these changes

2023-06-26 09:07 UTC, merged