JAX as Computation Backend similar to Pytorch, Tensorflow and Numpy
docarray/docarray pull request #1646
Opened 2023-06-14 03:49 UTC by agaraman0

2023-06-22 13:24 UTC, JoanFM requested changes

2023-06-22 13:24 UTC, JoanFM commented on docarray/computation/jax_backend.py
> +    pass
if not needed, just remove the import

2023-06-22 13:24 UTC, JoanFM commented on docarray/computation/jax_backend.py
> +def identity(array: jnp.ndarray) -> jnp.ndarray:
why is this needed?

2023-06-23 07:04 UTC, samsja commented on docarray/computation/jax_backend.py
> +        return cls._cast_output(jax.lax.stop_gradient(cls._get_tensor(tensor)))
not sure about calling this private method here :thinking:

2023-06-23 07:09 UTC, samsja reviewed
This looks mostly good ! Once we have :
* DocVec working
* Integration test


we will be good to go

2023-07-05 07:07 UTC, samsja commented on docarray/utils/_internal/misc.py
> +def is_jnp_available():
```suggestion
def is_jax_available():
```

lets rename it to this

2023-07-05 07:09 UTC, samsja commented on pyproject.toml
> +jax = {version = ">=0.4.10", optional = true}
can you add as well an `extra` section that install jax ?

it is right below this line.

And you need to add it to the all section as well

2023-07-05 07:12 UTC, samsja reviewed
looks really good. I added some tiny comments.

We are just missing the interagration test before we merge !

2023-07-05 07:14 UTC, samsja commented
btw looking at the CI it seems that you still have place where you load jax without using the helper import and therefore it throw an error

2023-07-05 07:20 UTC, JoanFM commented
Hey @agaraman0 ,

would it be possible for you to add a code snippet as an example of the usage of this feature in the PR description. Like this we can add it in future release notes to highlight this awesome feature.

2023-07-05 08:44 UTC, agaraman0 commented
> Hey @agaraman0 ,
> 
> would it be possible for you to add a code snippet as an example of the usage of this feature in the PR description. Like this we can add it in future release notes to highlight this awesome feature.

Sure will do that, I am just looking for some existing example if I can replicate one.

2023-07-14 13:10 UTC, JoanFM commented
@agaraman0 can you add an equivalent test to the one added for Pytorch and TF in this PR #1696

2023-07-14 14:24 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +        """Provide a compatible value that represents None in jax."""
```suggestion
        """Provide a compatible value that represents None in JAX."""
```

2023-07-14 14:31 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +            and returns them alongside their indices in the input `values`.
```suggestion
            Returns the k smallest values in `values` along with their indices.
```

2023-07-14 14:32 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +            Can also be used to retrieve the top k largest values,
```suggestion
            Can also be used to retrieve the k largest values,
```

2023-07-14 14:32 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +                Both ar of shape (n_queries, k)
```suggestion
                Both are of shape (n_queries, k)
```

2023-07-14 14:56 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +        :param eps: a small jitter to avoid divide by zero
```suggestion
        :param eps: a small jitter to avoid dividing by zero
```

2023-07-14 14:56 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +            :param eps: a small jitter to avoid divide by zero
```suggestion
            :param eps: a small jitter to avoid dividing by zero
```

2023-07-14 14:56 UTC, scott-martens commented on docarray/computation/jax_backend.py
> +            :param eps: a small jitter to avoid divde by zero
```suggestion
            :param eps: a small jitter to avoid dividing by zero
```

2023-07-14 14:59 UTC, scott-martens commented on docarray/typing/tensor/jaxarray.py
> +        Return the original ndarray without any memory copy.
```suggestion
        Return the original ndarray without making a copy in memory.
```

2023-07-14 15:00 UTC, scott-martens commented on docarray/typing/tensor/jaxarray.py
> +        The original view rest intact and is still a Document `JaxArray`
```suggestion
        The original view remains intact and is still a Document `JaxArray`
```

2023-07-14 15:01 UTC, scott-martens commented on docarray/typing/tensor/jaxarray.py
> +        the same memory layout.
```suggestion
        the same underlying memory.
```

2023-07-14 15:06 UTC, scott-martens reviewed
I think I found all docstrings. A few changes recommended.

2023-07-17 17:01 UTC, agaraman0 commented
Hey @samsja @JoanFM  PR is ready to be merged, addressing all concerns and review comments.

2023-07-18 06:57 UTC, samsja approved these changes
Great PR looking forward to merge

2023-07-18 08:12 UTC, JoanFM approved these changes

2023-07-18 08:12 UTC, merged