docs: adding field descriptions to predefined video document
docarray/docarray pull request #1775
Opened 2023-09-05 17:52 UTC by punndcoder28

* Adds field descriptions and example usage of each field for the predefined `Video` document

2023-09-05 17:53 UTC, punndcoder28 commented on docarray/documents/video.py
> +        description='Audio document document associated with the video',
@JoanFM Please let me know if this is a valid description and also an example for the field. Everything I could think of required a multiple line example

2023-09-05 17:54 UTC, punndcoder28 commented on docarray/documents/video.py
> +        `VideoNdArray`, `VideoTorchTensor`, `VideoTensorFlowTensor`''',
Skipping example here since we will need to do load tensor from video url and needs a multi-line example

2023-09-05 17:54 UTC, punndcoder28 commented on docarray/documents/video.py
> +    bytes_: Optional[VideoBytes] = Field(
Skipping example here since we will need to do get bytes from video url and needs a multi-line example

2023-09-06 07:11 UTC, samsja commented on docarray/documents/video.py
> +        description='URL to the remote video file that needs to be loaded',
```suggestion
        description='URL to a (potentially remote) video file that needs to be loaded',
```

2023-09-06 07:12 UTC, samsja commented on docarray/documents/video.py
> +        description='''Tensor object of the video which be specified to one of
```suggestion
        description='''Tensor object representing the video which be specified to one of
```

2023-09-06 07:13 UTC, samsja commented on docarray/documents/video.py
> +        Tensorflow, PyTorch, NumPy and Jax''',
```suggestion
        description='''Store an embedding: a vector representation of the Video ''',
```

2023-09-06 07:14 UTC, samsja commented on docarray/documents/video.py
> +        description='Bytes object of the video which is an instance of `VideoBytes`',
```suggestion
        description='Bytes represenation of the video 
```

2023-09-14 07:15 UTC, JoanFM requested changes

2023-09-14 07:15 UTC, JoanFM commented
To resolve the conflicts, make sure to add `None` as the default value for the Optional fields.

2023-09-14 17:10 UTC, JoanFM requested changes

2023-09-14 17:10 UTC, JoanFM commented on docarray/documents/video.py
> +        example='[0, 1, 2, 3, 4]',
```suggestion
        example=[0, 1, 2, 3, 4],
```

2023-09-14 17:10 UTC, JoanFM commented on docarray/documents/video.py
> +        example='[1, 0, 1]',
```suggestion
        example=[1, 0, 1],
```

2023-09-14 20:29 UTC, JoanFM requested changes

2023-09-14 20:29 UTC, JoanFM commented on docarray/documents/video.py
> +        description='Audio document document associated with the video',
document term is duplicated

2023-09-15 06:54 UTC, JoanFM requested changes

2023-09-15 06:54 UTC, JoanFM commented on docarray/documents/video.py
> +        description='Audio document document associated with the video',
```suggestion
        description='Audio document associated with the video',
```

2023-09-15 08:16 UTC, merged