fix: from_dataframe with numpy==1.26.1
docarray/docarray pull request #1823
Opened 2023-10-18 11:45 UTC by JohannesMessner

2023-10-18 14:57 UTC, JoanFM requested changes
Will a np.array of one dimension with 0 be considered a None?

2023-10-18 14:59 UTC, JohannesMessner commented
> Will a np.array of one dimension with 0 be considered a None?

No, it will not. It also wasn't before.

2023-10-18 15:08 UTC, JoanFM commented
> > Will a np.array of one dimension with 0 be considered a None?
> 
> No, it will not. It also wasn't before.

can we add a test for it?

2023-10-20 14:32 UTC, JoanFM requested changes

2023-10-20 14:32 UTC, JoanFM commented on docarray/display/document_summary.py
> +from typing import Any, List, Optional, Type, Union, get_args
does this exist in Python 3.8?

2023-10-23 07:36 UTC, JoanFM commented on docarray/display/document_summary.py
> +from typing import Any, List, Optional, Type, Union, get_args
Ok it is

2023-10-23 07:36 UTC, merged