Add flag to dis-able offset2id
docarray/docarray pull request #718
Opened 2022-11-03 02:09 UTC by dongxiang123

Goals:

- ...Add flag to disable offset2id in DocumentArray
- ...
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-11-04 08:33 UTC, JoanFM requested changes

2022-11-04 08:33 UTC, JoanFM commented on docarray/array/document.py
> +        offset2id: bool = True,
I think we should remove

2022-11-04 09:06 UTC, samsja commented
btw to fix the CI commit message you should rename offset2id to offsettoid (yes we don't allow number in the commit message :sweat_smile:

2022-11-07 07:17 UTC, samsja commented
@dongxiang123 Can you put a python snippet of the features in the docs description ?

2022-11-07 09:55 UTC, JoanFM requested changes

2022-11-07 09:55 UTC, JoanFM commented on docarray/array/storage/memory/getsetdel.py
> +            raise ValueError("Id2offset is disabled")
I think in the `DocumentArrayInMemory` this should not be applied. For the `InMemory` one the list-like behavior should always work

2022-11-07 09:55 UTC, JoanFM commented on docarray/array/storage/memory/getsetdel.py
> +        if self._enable_offset2id:
Do not touch the `InMemory` implementation

2022-11-07 13:25 UTC, JohannesMessner requested changes
Since this is a feature that we expect all backends to handle, we should adjust the documentation about "Add new Document Store" accordingly.

2022-11-07 15:53 UTC, samsja commented
Cannot we have this behavior shared across all of the backend ?

2022-11-07 15:58 UTC, JohannesMessner commented
> Cannot we have this behavior shared across all of the backend ?

Good point, I think we can. I think we can pass a flag to the `Offset2id` class that tells it to not do any syncing. Then `append` etc would just be no-ops that can be called from the backend with no effect. That way the backend would only have to pass the flag that it receives in its config to offset2id, once.

2022-11-07 22:24 UTC, alphinside commented
Hi, I see that the no offset2id flag is passed around to disable sync. Maybe you guys also can consider adding method to detect if the persisted data is having offset2id meta or not. This way it will avoid offset2id inconsistency issues when a Docarray is re-initialized again but somehow forgot to set the config of `enable_offset2id` to False, it will automatically assign to False rather than True

2022-11-08 04:41 UTC, dongxiang123 commented
@JohannesMessner @samsja This way sounds hacky to me, even if it is cleaner in this way, let's discuss this way in today's Daily.

2022-11-08 11:10 UTC, dongxiang123 commented
I created a new PR with new approach here. https://github.com/docarray/docarray/pull/730, and this one will be closed.

2022-11-08 11:10 UTC, closed without merging