fix: add num_worker argument to embed_and_evalute and pass label_tag
docarray/docarray pull request #731
Opened 2022-11-08 11:01 UTC by guenthermi

Goals:

- make it possible to use the `num_worker` attribute in the `embed_and_evaluate` function for the matching step
- pass the `label_tag` to the execution of `evaluate` in the  `embed_and_evaluate` function
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-11-08 14:10 UTC, bwanglzu reviewed
minor comment

2022-11-08 14:10 UTC, bwanglzu commented on docarray/array/mixins/evaluation.py
> +        num_worker: Optional[int] = 1,
remove Optional

2022-11-09 07:36 UTC, JoanFM approved these changes

2022-11-09 07:36 UTC, JoanFM requested changes
For the label tag, it seems there should be a test covering it

2022-11-09 08:37 UTC, JoanFM approved these changes

2022-11-09 12:50 UTC, merged