feat: update weaviate server to v1.16.0 and client to 3.9.0
docarray/docarray pull request #736
Opened 2022-11-08 15:42 UTC by dirkkul

Based on https://github.com/docarray/docarray/pull/734

Goals:
- [x] update weaviate server and weaviate client
- [x] update some python client calls to include class names
- [x] update some of the tests

2022-11-08 15:52 UTC, alaeddine-13 requested changes

2022-11-08 15:52 UTC, alaeddine-13 commented on tests/unit/array/mixins/test_find.py
> +        ('weaviate', {'n_dim': 32, "distance": "cosine"}),
```suggestion
        ('weaviate', {'n_dim': 32, 'distance': 'cosine'}),
```

2022-11-08 15:52 UTC, alaeddine-13 commented on tests/unit/array/mixins/test_find.py
> +    if storage == "weaviate":
```suggestion
    if storage == 'weaviate':
```

2022-11-08 15:52 UTC, alaeddine-13 commented on tests/unit/array/mixins/test_find.py
> +        result = da.find(query, limit=limit, additional=["certainty"])
```suggestion
        result = da.find(query, limit=limit, additional=['certainty'])
```

2022-11-08 15:52 UTC, alaeddine-13 commented on tests/unit/array/storage/weaviate/test_query_params.py
> +        additional=["certainty"],
```suggestion
        additional=['certainty'],
```

2022-11-08 15:52 UTC, alaeddine-13 commented on tests/unit/array/storage/weaviate/test_query_params.py
> +    da = DocumentArray(storage="weaviate", config={"n_dim": 10, "distance": "cosine"})
```suggestion
    da = DocumentArray(storage='weaviate', config={'n_dim': 10, 'distance': 'cosine'})
```

2022-11-08 16:10 UTC, dirkkul commented on docarray/array/storage/weaviate/getsetdel.py
> +            self._client.data_object.delete(wid, class_name=self.name)
please have a look if it's ok!

2022-11-09 07:18 UTC, alaeddine-13 commented on docarray/array/storage/weaviate/getsetdel.py
> +            self._client.data_object.delete(wid, class_name=self.name)
looks good to me, let's try to pass CI

2022-11-09 10:45 UTC, alaeddine-13 approved these changes

2022-11-09 10:46 UTC, merged