docs: add colab notebook for interactive 3d data visualization
docarray/docarray pull request #749
Opened 2022-11-10 16:23 UTC by anna-charlotte

Goals:

Add a link to a Google Colab notebook to demonstrate DocArray's 3d data handling and interactive visualization. Prepare examples for DocArrays point cloud representation as well as vertices and faces representation for users to interact with.

- [x] add colab link to docs
- [x] prepare notebook
- [x] prepare data and push to Jina Hub

2022-11-10 21:46 UTC, JoanFM requested changes
make sure to check the login functionality in the notebook.

Also, remember once released, to simply do `pip install docarray`. Why is `full` needed is not clear to me

2022-11-11 08:33 UTC, JohannesMessner commented
> @JoanFM The login works. W.r.t. the installation, I think as of right now, `trimesh` is only installed with the `pip install "docarray[full]"`, not with the basic install though. Should I do `pip install docarray, trimesh` instead?
> 
> <img alt="image" width="1481" src="https://user-images.githubusercontent.com/73693835/201295490-3008d561-e6bb-45cf-bc73-ba565b425fdc.png">

Didn't we at some point want to offer installs for different modalities, like `pip install docarray[3dmesh]`? Might be worth revisiting this idea

2022-11-11 09:34 UTC, samsja commented
I believe we need to have the notebook as well in the repo

2022-11-11 15:56 UTC, samsja approved these changes

2022-11-11 16:05 UTC, JoanFM approved these changes

2022-11-11 16:06 UTC, JoanFM approved these changes

2022-11-11 16:06 UTC, merged