docs: add docs about list-like feature
docarray/docarray pull request #762
Opened 2022-11-14 03:55 UTC by dongxiang123

Signed-off-by: dong xiang <iamxiangdong@gmail.com>

Goals:
Since this [PR](https://github.com/docarray/docarray/pull/730/files#diff-ed0be5f19866ce0e879e0ad77f486223c573998977944684dc03499250e5089b) is merge and we need to add document about constructing a new backend in the document
- ...
- ...
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-11-14 08:09 UTC, JoanFM requested changes

2022-11-14 10:18 UTC, dongxiang123 commented on docs/advanced/document-store/extend.md
> +da = DocumentArray(storage='qdrant', config={'n_dim':3, 'list_like':False})
Make sense

2022-11-14 11:55 UTC, JohannesMessner commented
I think we need to explain that this `list_like` parameter has to be part of the `config`, and then how it is passed to the `__init__` of `Offsed2ID`.

2022-11-14 15:44 UTC, dongxiang123 commented
> I think we need to explain that this `list_like` parameter has to be part of the `config`, and then how it is passed to the `__init__` of `Offsed2ID`.

added examples.

2022-11-15 11:05 UTC, JohannesMessner requested changes

2022-11-15 11:05 UTC, JohannesMessner commented on docs/advanced/document-store/extend.md
> +member variable by passing list_like flag as follows:
```suggestion
want to also persist the ordering of Documents inside the storage. However, the list-like
structure implemented by Offset2id can introduce performance bottlenecks, so you can disable this feature by passing a flag when constructing the backend.

In your backend implementations, in `getsetdel.py`, you have to construct the _offset2ids 
member variable by passing list_like flag as follows:
```

2022-11-15 11:05 UTC, JohannesMessner commented on docs/advanced/document-store/extend.md
> +The `list-like` flag is passed into the config file as follows:
```suggestion
To enable the disabling of list-like features, your configuration should accept the flag `list_like` as follows:
```

2022-11-15 11:05 UTC, JohannesMessner commented on docs/advanced/document-store/extend.md
> +By default, it is set to be `True`.
```suggestion
By default, this should be set to be `True`.

Further, you have to store the value of this flag in `self._list_like`. Some methods that are handled outside of your control will take the value form there and use it appropriately.
```

2022-11-15 12:16 UTC, JoanFM requested changes

2022-11-15 12:16 UTC, JoanFM commented on docs/advanced/document-store/extend.md
> +    list - like: True
```suggestion
    list_like: bool
```

2022-11-15 13:48 UTC, alexcg1 requested changes

2022-11-15 13:48 UTC, alexcg1 commented on docs/advanced/document-store/extend.md
> +member variable by passing list_like flag as follows:
```suggestion
want to also persist the ordering of Documents inside the storage. Considering the performance cost brought by the list-like structure implemented by Offset2id, you can disable this feature by passing a flag when constructing the backend.
After this, the Offset2id will become a shell and do nothing. Then in the `getsetdel.py` you can construct the `_offset2ids` 
member variable by passing the `list_like` flag as follows:
```

2022-11-15 13:48 UTC, alexcg1 commented on docs/advanced/document-store/extend.md
> +For the reason to support the list-like feature, the list-like APIs should do flag checking only when the offset2id structure is called as follows:
```suggestion
To support the list-like feature, the list-like APIs should perform flag checking only when the offset2id structure is called as follows:
```

2022-11-15 13:48 UTC, alexcg1 commented on docs/advanced/document-store/extend.md
> +By default, it is set to be `True`.
```suggestion
By default, it is set to `True`. 
```

2022-11-15 14:05 UTC, JohannesMessner commented on docs/advanced/document-store/extend.md
> +structure implemented by Offset2id can introduce performance bottlenecks, so you can disable this feature by passing a flag when constructing the backend.
```suggestion
structure implemented by Offset2id can introduce performance bottlenecks, so you can disable this feature by passing a flag when constructing the backend.

In step 4 you will see how you should read in this flag (`list_like`) from the user. Here you have to use it do adapt some operations.
```

2022-11-15 14:07 UTC, JoanFM approved these changes

2022-11-15 14:07 UTC, merged