fix: remove cosine similarity field with false assignment
docarray/docarray pull request #835
Opened 2022-11-23 11:03 UTC by anna-charlotte

Signed-off-by: anna-charlotte <charlotte.gerhaher@jina.ai>

In the weaviate storage backend, the `distance` is mistakenly being assigned to the `cosine_similarity` field. Remove this line, since weaviate does not provide cosine similarity, but instead (cosine) distance. 

Added some more documentation on the keys to access in the `.scores` dictionary, since most are different to the default.

Goals:

- [x] Remove `cosine_similarity` assignment from weaviate backend.
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-11-28 09:38 UTC, alexcg1 requested changes

2022-11-28 09:38 UTC, alexcg1 commented on docs/advanced/document-store/elasticsearch.md
> +Then the search with the proposed filter can be implemented and used with the following code. Also, it is noted, that for Elasticsearch, the distance scores can be accessed in the Document's `.scores
```suggestion
Then the search with the proposed filter can be implemented and used with the following code. Note: For Elasticsearch, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'score'`.
```

2022-11-28 09:38 UTC, alexcg1 commented on docs/advanced/document-store/redis.md
> +Then the search with the proposed filter can be used as follows. Also, it is noted, that for Redis, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'score'`.
```suggestion
Then the search with the proposed filter can be used as follows. Note: For Redis, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'score'`.
```

2022-11-28 09:38 UTC, alexcg1 commented on docs/advanced/document-store/weaviate.md
> +It is noted, that for Weaviate, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'distance'`.
```suggestion
Note: For Weaviate, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'distance'`.
```

2022-11-28 11:43 UTC, alexcg1 approved these changes
LGTM :+1:

2022-11-28 11:50 UTC, JoanFM requested changes

2022-11-28 11:50 UTC, JoanFM commented on docs/advanced/document-store/elasticsearch.md
> +Then the search with the proposed filter can be implemented and used with the following code. Note: For Elasticsearch, the distance scores can be accessed in the Document's `.scores` dictionary under
There is a different way to append `notes`. @JohannesMessner please suggest

2022-11-28 11:50 UTC, JoanFM commented on docs/advanced/document-store/redis.md
> +Then the search with the proposed filter can be used as follows. Note: For Redis, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'score'`.
same here, if we add Note we should add it properly, otherwise remove `Note`

2022-11-28 11:50 UTC, JoanFM commented on docs/advanced/document-store/weaviate.md
> +Note: For Weaviate, the distance scores can be accessed in the Document's `.scores` dictionary under the key `'distance'`.
same here

2022-11-28 13:22 UTC, JoanFM requested changes
Should we have a common key in `scores` for every docstore besides an specialized one? like this is easier to have same code for every backend?

2022-12-01 09:51 UTC, JohannesMessner approved these changes

2022-12-01 09:55 UTC, merged