Feat opensearch integration
docarray/docarray pull request #853
Opened 2022-11-25 18:18 UTC by jay-bhambhani

Goals:

-  Integrating OpenSearch with DocArray
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-11-28 08:57 UTC, JohannesMessner commented
Hi @jay-bhambhani, thanks for your contribution, we are rally excited about additional storage options for DocArray!

I approved you for CI runs, but to get it going you will have to apply `black` and `flake8` to your code, in order to make it uniform in terms of style. This should be very quick, and can be done automatically for every commit by installing the respective [pre-commit hooks.](https://github.com/docarray/docarray/blob/main/CONTRIBUTING.md#install-pre-commit-hooks).
I think you also need to fix the indentation [here](https://github.com/docarray/docarray/pull/853/files#diff-06d2e2efa25b9e89e3f91a3532856e3a0e83a266089c20ee69c87a4283c0bf51R157) before the rest will run.

I will start reviewing this PR soon, but if you have any questions in the meantime, please just ping me here!

2022-11-28 16:58 UTC, jay-bhambhani commented
> done

Hi @JohannesMessner - excited to contribute in some way! Definitely will take a look - it might take a little bit because my laptop unfortunately crapped out on me. But - just wanted to let you know so you don't think I've disappeared!

2022-12-04 00:40 UTC, kdewald commented on docs/advanced/document-store/opensearch.md
> +# Elasticsearch
Incorrect reference

2022-12-04 00:40 UTC, kdewald commented on docs/advanced/document-store/opensearch.md
> +    name: elastic
Update references to OpenSearch

2022-12-04 00:40 UTC, kdewald commented on docs/advanced/document-store/opensearch.md
> +(elasticsearch)=
Update references to OpenSearch

2022-12-04 00:41 UTC, kdewald commented on docs/advanced/document-store/opensearch.md
> +        'hosts': 'https://elastic:PRq7je_hJ4i4auh+Hq+*@localhost:9200',
Update example for OpenSearch

2022-12-04 00:41 UTC, kdewald commented on docs/advanced/document-store/opensearch.md
> +Consider you store Documents with a certain tag `price` into ElasticSearch and you want to retrieve all Documents
Update references to OpenSearch

2022-12-04 00:41 UTC, kdewald commented on docs/advanced/document-store/opensearch.md
> +| `index_name`      | Elasticsearch index name; the class name of Opensearch index object to set this DocumentArray                                          | None
Update references to OpenSearch

2022-12-04 00:42 UTC, kdewald commented on docarray/array/storage/opensearch/seqlike.py
> +        :return: the length of this :class:`DocumentArrayElastic` object
Should be `DocumentArrayOpenSearch`

2022-12-04 00:42 UTC, kdewald commented on docarray/array/storage/opensearch/seqlike.py
> +        """Return the string representation of :class:`DocumentArrayElastic` object
Should be `DocumentArrayOpenSearch`

2022-12-04 00:42 UTC, kdewald commented on docarray/array/storage/opensearch/getsetdel.py
> +        :return: the retrieved document from elastic
Update reference to OpenSearch

2022-12-04 00:42 UTC, kdewald commented on docarray/array/storage/opensearch/getsetdel.py
> +        :raises KeyError: raise error when elastic id does not exist in storage
Update reference to OpenSearch

2022-12-04 00:42 UTC, kdewald commented on docarray/array/storage/opensearch/backend.py
> +        """Update the offset2ids in elastic"""
Update reference to OpenSearch

2022-12-04 00:42 UTC, kdewald commented on docarray/array/storage/opensearch/backend.py
> +        """Return the offset2ids stored in elastic
Update reference to OpenSearch

2022-12-05 10:55 UTC, JohannesMessner requested changes
I had a look, but I am not really familiar with OpenSearch (or even ES, for that matter), so could someone else chime in? @alaeddine-13 @violenil?

2022-12-05 10:55 UTC, JohannesMessner commented on docarray/array/storage/opensearch/backend.py
> +        ...  # ensure unique identifiers here
```suggestion
```

2022-12-05 10:55 UTC, JohannesMessner commented on docarray/array/storage/opensearch/backend.py
> +                                #'encoder': opensearch_config.encoder,
what about these comments?

2022-12-06 16:11 UTC, JohannesMessner commented
> thanks @JohannesMessner! will apply the feedback and continue chugging through these. one quick question - seeing this failure: hubble.excepts.AuthenticationRequiredError: -1: Jina auth token is not provided or has expired. <function PushPullMixin.push at 0x7f1321a538c0> requires login to Jina AI, please do `jina auth login -f` or set env variable `JINA_AUTH_TOKEN. how can i take care of this?

I think you can ignore all the tests that fail due to this. We will probably end up moving these tests out of DocArray anyways

2022-12-06 21:46 UTC, jay-bhambhani commented
> > thanks @JohannesMessner! will apply the feedback and continue chugging through these. one quick question - seeing this failure: hubble.excepts.AuthenticationRequiredError: -1: Jina auth token is not provided or has expired. <function PushPullMixin.push at 0x7f1321a538c0> requires login to Jina AI, please do `jina auth login -f` or set env variable `JINA_AUTH_TOKEN. how can i take care of this?
> 
> I think you can ignore all the tests that fail due to this. We will probably end up moving these tests out of DocArray anyways

Awesome! Thanks. Sorry one more - I don't know what I'm breaking with commitlint. Can I please ask for a bit of assistance? I'll update the docs accordingly as well.

Thank you so much for your help!
Jay

2022-12-08 21:06 UTC, jay-bhambhani commented
OK! Looks like the only tests that aren't passing are related to this JINA_AUTH_TOKEN issue. If somebody could please take a look!

2022-12-09 15:31 UTC, alexcg1 requested changes
Looks good from a preliminary docs check. Just a few small tweaks

2022-12-09 15:31 UTC, alexcg1 commented on docs/advanced/document-store/opensearch.md
> +One can use [Opensearch](https://opensearch.org/) as the document store for DocumentArray. It is useful when one wants to have faster Document retrieval on embeddings, i.e. `.match()`, `.find()`.
Could you change from "one" to "you" throughout the doc please? To follow our updated style guidelines (updated like yesterday - they're not public yet)

2022-12-09 15:31 UTC, alexcg1 commented on docs/advanced/document-store/opensearch.md
> +You can customize how bulk requests is being sent to Opensearch when adding documents by adding additional `kwargs` on `extend` method call. See [the official Documentation](https://opensearch.org/do
```suggestion
You can customize how bulk requests are sent to Opensearch when adding Documents by adding additional `kwargs` on `extend` method call. See [the official documentation](https://opensearch.org/docs/1.2/opensearch/rest-api/document-apis/bulk/) for more details. See the following code for example:
```

2022-12-09 15:31 UTC, alexcg1 commented on docs/advanced/document-store/opensearch.md
> +Consider Documents with embeddings `[0,0,0]` up to `[9,9,9]` where the document with embedding `[i,i,i]`
```suggestion
Consider Documents with embeddings `[0,0,0]` up to `[9,9,9]` where the Document with embedding `[i,i,i]`
```

2022-12-09 15:31 UTC, alexcg1 commented on docs/advanced/document-store/opensearch.md
> +prices must follow a filter. As an example, let's consider that retrieved documents must have `price` value lower
Please ensure all occurrences of `Document` or `DocumentArray` are capitalized (since they are a class in DocArray)

2022-12-09 15:31 UTC, alexcg1 commented on docs/advanced/document-store/opensearch.md
> +## Config
```suggestion
## Configuration
```

2022-12-09 15:31 UTC, alexcg1 commented on docs/advanced/document-store/opensearch.md
> +The following configs can be set:
```suggestion
```

This is redundant (I removed the line from other document store docs in a PR earlier today)

2022-12-12 13:17 UTC, alexcg1 approved these changes
LGTM :+1:

2022-12-12 15:52 UTC, merged

2022-12-12 15:53 UTC, JoanFM commented
Thanks a lot for your contribution @jay-bhambhani

2022-12-12 15:54 UTC, jay-bhambhani commented
Glad I could be of service! I'll keep adding and improving things as we go! Great project!