feat: store distance scores in scores dict
docarray/docarray pull request #873
Opened 2022-11-29 10:37 UTC by anna-charlotte

Signed-off-by: anna-charlotte <charlotte.gerhaher@jina.ai>

Goals:
Milvus: Store distance scores in a `Document`'s `.scores` dictionary, under the key `'score'` to enable accessing those scores.

- [x] store distance values in `.scores` dict with `key = 'score'`
- [x] update milvus documentation
- [x] update 'Add New Document Store' section in documentation

2022-11-29 15:35 UTC, alexcg1 approved these changes
LGTM :+1:

2022-11-29 18:15 UTC, JohannesMessner requested changes

2022-11-29 18:15 UTC, JohannesMessner commented on docarray/array/storage/milvus/backend.py
> +                doc.scores[f'score'] = NamedScore(value=hit.score)
Is there a way we can know the score that was used? I think it is in the config, can we use that as the key here? how do other backends handle that?

2022-11-30 08:31 UTC, JohannesMessner requested changes

2022-11-30 08:31 UTC, JohannesMessner commented on docs/advanced/document-store/milvus.md
> +````
this should be adapted to the new key in the scores dict

2022-11-30 10:51 UTC, JohannesMessner approved these changes
LGTM! There is one test failing unexpectedly, should not be related, but let's restart the CI before we merge

2022-11-30 14:07 UTC, merged