feat(v2): add 3d data handling
docarray/docarray pull request #925
Opened 2022-12-09 13:39 UTC by anna-charlotte

Goals:

- [x] add MeshUrl
- [x] add tests for MeshUrl
- [x] add PointCloudUrl
- [x] add tests for PointCloudUrl
- [x] add predefined Mesh Document
- [x] add predefined PointCloud Document
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-12-12 15:10 UTC, samsja commented on docarray/predefined_document/mesh.py
> +class Mesh(BaseDocument):
lets rename 3dMesh

2022-12-12 15:11 UTC, samsja commented on docarray/predefined_document/mesh.py
> +class Mesh(BaseDocument):
or 3DMesh

2022-12-12 15:11 UTC, samsja commented on docarray/predefined_document/point_cloud.py
> +class PointCloud(BaseDocument):
same lets rename 3d point cloud

2022-12-12 15:13 UTC, samsja commented on docarray/typing/url/helper_3d_data.py
> +from typing import TYPE_CHECKING, Optional, Union
lets create 3dUrl under url

2022-12-12 15:14 UTC, samsja commented on docarray/typing/url/mesh_url.py
> +class MeshUrl(AnyUrl):
lets have an abstract 3dUrl class that implement the `_load_trimesh_instace` rather than having it in the helper

2022-12-12 15:15 UTC, samsja commented on tests/integrations/predefined_document/test_mesh.py
> +REMOTE_OBJ_FILE = 'https://people.sc.fsu.edu/~jburkardt/data/obj/al.obj'
can we have a none remote obj as well ?

2022-12-12 15:16 UTC, samsja commented on tests/integrations/predefined_document/test_point_cloud.py
> +REMOTE_OBJ_FILE = 'https://people.sc.fsu.edu/~jburkardt/data/obj/al.obj'
same can we have a non remote obj as well ?

2022-12-12 15:33 UTC, JohannesMessner requested changes

2022-12-12 15:33 UTC, JohannesMessner commented on docarray/predefined_document/mesh.py
> +    It can contain an MeshUrl (`Mesh.url`), a Tensor (`Mesh.tensor`),
what about vertices, faces?

2022-12-12 16:42 UTC, samsja commented on pyproject.toml
> +
why is this needed ?

2022-12-13 08:29 UTC, samsja commented on pyproject.toml
> +
okay makes sense

2022-12-14 08:22 UTC, samsja commented on docarray/typing/url/url_3d/mesh_url.py
> +            from docarray.typing.url.mesh_url import Mesh3DUrl
```suggestion
            from docarray.typing import Mesh3DUrl
```

2022-12-14 08:48 UTC, JohannesMessner requested changes
Just one thing, can you adjust the class docstrings for MeshUrl, PointCloudUrl, and Url3d? Right now they all say the same thing, as a user which one should I use when? Or is it self-explanatory for someone that (unlike me) knows what they are doing with 3D stuff?

2022-12-14 10:02 UTC, JohannesMessner approved these changes

2022-12-14 10:37 UTC, merged