fix: calculate relevant docs on index instead of queries
docarray/docarray pull request #950
Opened 2022-12-15 15:34 UTC by guenthermi

Goals:

- The `num_relevant_documents_per_label` is calculated in the `embed_and_evaluate` method on the documents in `self`. However, this is only correct if `self` is matched against itself. Instead it should be calculated on the `index_data` attribute if it is provided.

- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-12-15 15:38 UTC, JoanFM requested changes
Put it as draft until really ready for review

2022-12-15 15:38 UTC, JoanFM commented on tests/unit/array/mixins/oldproto/test_eval_class.py
> +    print(res)
remove print, there should be assertions

2022-12-15 15:47 UTC, LMMilliken commented on tests/unit/array/mixins/oldproto/test_eval_class.py
> +    metric_names = ['precision_at_k', 'reciprocal_rank', 'recall_at_k']
Maybe add a test case for `exclude_self` = True/False

2022-12-15 20:50 UTC, JoanFM approved these changes

2022-12-16 10:41 UTC, gmastrapas approved these changes

2022-12-16 15:16 UTC, merged