feat: add 'nested' to elasticsearch
docarray/docarray pull request #959
Opened 2022-12-21 15:00 UTC by AnneYang720

Signed-off-by: AnneY <evangeline-lun@foxmail.com>

Goals:

This PR is related to issue #958 
According to [ElasticSearch's documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html), nested field objects can be searched with nested query.

- [ ] add code
- [ ] add test case
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-12-22 09:16 UTC, alaeddine-13 commented on docarray/array/storage/elastic/backend.py
> +                }
```suggestion
            col_config = {
                'type': self._map_type(coltype),
            }
            if coltype != 'nested':
                col_config['index'] = True
```

2022-12-22 09:18 UTC, alaeddine-13 commented on tests/unit/array/mixins/test_find.py
> +                    'field_2': {'field_2_1': f'world_{i}'},
why do we create 2 nested fields if we only test on the first one ?

2022-12-29 08:31 UTC, JoanFM requested changes

2022-12-29 08:31 UTC, JoanFM commented on tests/unit/array/mixins/test_find.py
> +            "path": "field",
please be coherent and use single quotes

2022-12-30 10:17 UTC, alaeddine-13 approved these changes

2023-03-01 11:05 UTC, samsja commented
I think we can close this PR

2023-03-01 11:05 UTC, closed without merging