feat: add color to point cloud display
docarray/docarray pull request #961
Opened 2022-12-27 08:41 UTC by anna-charlotte

Signed-off-by: anna-charlotte <charlotte.gerhaher@jina.ai>

When displaying a point cloud, we want to additionally consider its colors, if those are available. 
The point cloud tensor is stored in a Documents `.tensor` field. If colors are available store them in a chunk `Document` with `tags['name'] = 'point_cloud_colors'`. The chunks tensor must be of shape (n_points, 3) or (n_points, 4), with a corresponding color for each point.

- [x] check for point_colors in `display_point_cloud_tensor()`
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-12-27 14:07 UTC, JoanFM requested changes
add a test to show that at least it does not break

2022-12-27 14:08 UTC, JoanFM requested changes

2022-12-27 14:08 UTC, JoanFM commented on docarray/document/mixins/plot.py
> +                and chunk.tags['name'] == 'point_colors'
this point_colors string should come from some common variable, otherwise is just a magic name

2022-12-28 14:06 UTC, JoanFM commented on docarray/document/mixins/plot.py
> +                and chunk.tags['name'] == 'point_colors'
yes

2022-12-29 07:27 UTC, JoanFM requested changes

2022-12-29 07:27 UTC, JoanFM commented on tests/unit/document/test_summary.py
> +    os.environ['DISPLAY'] = ':1'
see in jina how in tests some env vars are set. This should be set in a fixture so that later the value can be reset to the old value

2023-01-02 09:36 UTC, samsja commented on docarray/document/mixins/mesh.py
> +class PointCloud:
lets use proper python ENUM here : https://docs.python.org/3/library/enum.html

2023-01-02 09:36 UTC, samsja commented on docarray/document/mixins/mesh.py
> +class PointCloud:
and lets call it PointCloud Enum

2023-01-02 09:36 UTC, samsja commented on docarray/document/mixins/plot.py
> +                and (chunk.tensor.shape[-1] == 3 or chunk.tensor.shape[-1] == 4)
```suggestion
                and chunk.tensor.shape[-1] in [3, 4]

```

2023-01-02 09:36 UTC, samsja commented on docs/datatypes/mesh/index.md
> +```python
is there a way we can load both color and data from some files ?

2023-01-02 09:36 UTC, samsja commented on setup.py
> +            'trimesh[easy]',
what is the difference with easy ?

2023-01-02 09:48 UTC, JohannesMessner requested changes
Did you remove the test that you mention in the comment here?

2023-01-02 09:48 UTC, JohannesMessner commented on docarray/document/mixins/plot.py
> +                'name' in chunk.tags.keys()
Is `'name`' a key that is already established in other parts of the code / other features? If not I think I would prefer a more descriptive key here

2023-01-02 09:48 UTC, JohannesMessner commented on docs/datatypes/mesh/index.md
> +```
Maybe we can switch this code snippet around to first load the point coordinate like always, and then add the color chunk in a second step

2023-01-02 09:49 UTC, samsja commented on docs/datatypes/mesh/index.md
> +```python
okay I see and in practice how would I load the color with trimesh ? How do I get this colors array ?

2023-01-02 10:56 UTC, samsja commented on docs/datatypes/mesh/index.md
> +```python
okay I see makes sense then

2023-01-03 08:31 UTC, samsja commented on setup.py
> +            'pyglet<=1.5.27',  # required by trimesh
Why is the reason not to let trimesh handle this dependency capping ?

2023-01-03 12:51 UTC, JohannesMessner commented on docarray/document/mixins/plot.py
> +                'name' in chunk.tags.keys()
no sounds good, let's keep it consistent

2023-01-03 12:52 UTC, JohannesMessner approved these changes

2023-01-03 12:55 UTC, JoanFM approved these changes

2023-01-06 10:15 UTC, merged